### ISSUE TITLE
File upload feature in explorer (nice to have)

### ISSUE THREAD

**Issue by adnanshatil** [strongloop/loopback-component-explorer#103]
We can create API for file upload and download. But there is no way to test it from explorer. 
It'd be nice to have that feature. 

Right now there is an example with angular but that requires some work.

Sorry, if it is already duplicated.

**Comment by gausie** [comment]
+1

There seems to be a dataType in the newest swagger-ui for `file`, so this shouldn't be too difficult.

**Comment by bajtos** [comment]
:+1: 

There is a catch though: at the moment, we don't have a good way how to say that a remote method accepts/returns a file. We need to improve strong-remoting to support files - see https://github.com/strongloop/strong-remoting/issues/35

**Comment by diaswrd** [comment]
:+1: That would be awesome.

**Comment by barocsi** [comment]
+1 Awaiting for this

**Comment by mike-aungsan** [comment]
+1

**Comment by benawarez** [comment]
has the File Upload/Download API been created?  I'm trying to use this one but I keep running into errors:

loopback-component-storage-mongo

Issue reported:
https://github.com/jdrouet/loopback-component-storage-mongo/issues/2

**Comment by gaohailang** [comment]
+1

**Comment by sachinhub** [comment]
+1 Awaiting support for this in loopback. Is it already done?

**Comment by htmlauthor** [comment]
+1 for this to get implemented. If we use API explorer as an example of how to use our API's, we should be able to demonstrate file upload as well.

**Comment by deviant32** [comment]
+1 Need this so I don't have to keep switching to postman.

**Comment by gbejic** [comment]
+1 we use explorer for admins to upload files and need that too.

**Comment by Rikhart** [comment]
+1 what about this feature, I need too
