### ISSUE TITLE
Support default status codes

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#105]
The generated swagger spec should include status codes sourced from the `sharedMethod.http.status` / `sharedMethod.http.errorStatus`, see https://github.com/strongloop/strong-remoting/pull/218.

Although I'm not sure how the mapping should look exactly...

**Comment by bajtos** [comment]
:+1:

**Comment by bajtos** [comment]
@0candy The goal of this task is to add support for the new feature landed by https://github.com/strongloop/strong-remoting/pull/218:

In short, method's `http` object supports two new config options `status` and `errorStatus`, see this example:

```
{
  isStatic: true,
  accepts: [],
  returns: [],
  http: {
    status: 201,
    errorStatus: 508 
  }
}
```

When set, the values override the default success status code (200) and the default error status code (500).

The current implementation in loopback-swagger uses hard-coded 200, see https://github.com/strongloop/loopback-swagger/blob/9a30a143a47445f321c1d349c5b808517e248686/lib/specgen/route-helper.js#L126-L127

>```js
var defaultCode = route.returns && route.returns.length ? 200 : 204;
// TODO - support strong-remoting's option for a custom response code
var responseMessages = {};
responseMessages[defaultCode] = {
  description: 'Request was successful',
  schema: returns,
  // TODO - headers, examples
};
```

There is no default error status described, I think we should add one if the list of know error does not cover it. See https://github.com/strongloop/loopback-swagger/blob/9a30a143a47445f321c1d349c5b808517e248686/lib/specgen/route-helper.js#L136-L147:

>```js
if (route.errors) {
  // TODO define new LDL syntax that is status-code-indexed
  // and which allow users to specify headers & examples
  route.errors.forEach(function(msg) {
    responseMessages[msg.code] = {
      description: msg.message,
      schema: schemaBuilder.buildFromLoopBackType(msg.responseModel,
                                                  typeRegistry),
      // TODO - headers, examples
    };
  });
}
```

**Comment by 0candy** [comment]
-[ ] Add support for status
-[ ] Add support for errorStatus
