### ISSUE TITLE
Custom routes in bootscripts

### ISSUE THREAD

**Issue by danielrvt** [strongloop/loopback-component-explorer#109]
It would be nice if we had a way to add custom routes defined in a bootscript to the explorer. 
It would also be nice if we could specify some options like params, headers, response and a description to the explorer.

**Comment by bajtos** [comment]
@danielrvt this is interesting idea. Could you please provide an example of such route? Is there any particular reason why your route is not implemented as a remote method via strong-remoting?

**Comment by SamiSammour** [comment]
Are you kidding me guys??? How could this such an important feature not yet implemented!!!
Day after day I regret choosing loopback as a web framework... so much work to be done yet so poorly documented

**Comment by Elrendio** [comment]
Hello, 

here's my use case and why I would need this feature (and apparently I'm not alone ^^): 
I coded a console API for company inner resources (adding and removing Interns, employees, booking meeting, ...) 
We're looking to recruit and to contact potentiel candidates we extract their email from their github account. I have a custom endpoint taking as params the username of the targeted github account and giving back their email. I feel like creating a model only for this feature is too much and I have no models where I could add this as a remote method. I'd like to test my feature in the explorer.

Thanks for reading.

**Comment by bajtos** [comment]
> We're looking to recruit and to contact potentiel candidates we extract their email from their github account. I have a custom endpoint taking as params the username of the targeted github account and giving back their email. I feel like creating a model only for this feature is too much and I have no models where I could add this as a remote method. I'd like to test my feature in the explorer.

I am afraid in LoopBack 3.x, it's a fundamental part of the design that all remote methods are living in an object (a model) and each model acts also as a controller.

My recommendation is to create a new model that's inheriting from `Model` (not `PersistedModel`!) and put all your "extra" routes into that model. Think of it as `UtilController` containing various utility methods, not as a new model class persisted in a database.

In the upcoming version 4.0, we have APIs to define REST endpoints using route-based approach, see https://loopback.io/doc/en/lb4/Routes.html#using-partial-openapi-spec-fragments
