### ISSUE TITLE
Swagger: skipping unknown type "ObjectID".

### ISSUE THREAD

**Issue by cebor** [strongloop/loopback-component-explorer#126]
Since i upgraded to the new explorer i get following error/warning when starting my app:

```
$ node .
Swagger: skipping unknown type "ObjectID".
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
```

I followed the migration guide in the README.

My app: https://github.com/loggrio/loggr-api

**Comment by raymondfeng** [comment]
@bajtos What does MongoDB ObjectID mapped to swagger? It probably should be string.

**Comment by bajtos** [comment]
Here is what I think should be done about this issue:

 - Run the app against loopback-explorer@1.x and 2.x, compare the generated model definitions.
 - Fix loopback-swagger to generate appropriate type for ObjectID, e.g. a string as @raymondfeng suggested.

**Comment by alexthewilde** [comment]
+1

**Comment by steve8708** [comment]
+1, would love to get rid of this error message :)

**Comment by rootical** [comment]
Guys, please fix this :+1:

**Comment by bajtos** [comment]
@rootical `skipping unknown type "ObjectID"` is just a warning, it's almost certainly unrelated to the error you are seeing later.

**Comment by cebor** [comment]
@bajtos yes it is just a warning, but also all schemas with ObjectId or a ForeignKey are not correct.

Example: http://loggr.stkn.org/explorer/#!/Metering/Metering_create

The Metering model in the example should have an Id, and two ForeignKeys, which not appear in the Schema.

**Comment by listepo** [comment]
+1

**Comment by sguilly** [comment]
+1

**Comment by raymondfeng** [comment]
@bajtos Can we map ObjectID to string for now?

**Comment by bajtos** [comment]
Yes, I think that's the right approach. Plus add a regex pattern to ensure the string is a valid ObjectID (24 hex digits IIRC).

**Comment by saystone** [comment]
+1

**Comment by Vrolijkx** [comment]
+1

**Comment by omega500** [comment]
+1 Also have a warning on GeoPoint object

**Comment by MrBoolean** [comment]
+1

**Comment by sebastianhaas** [comment]
+1 for `ObjectID` and +1 for `GeoPoint`

**Comment by benawarez** [comment]
+1 for GeoPoint and +1 for ObjectID

**Comment by Alcal** [comment]
I discovered that my problem came from the fact that  I was specifying an "id" field in my model definitions, so while the connector generated the objectID in mongo, it left MY id blank and returned nulls. Once I removed my id field, I stopped getting the error and started getting the true ID's

**Comment by mike-aungsan** [comment]
Same issue
