### ISSUE TITLE
Operation IDs should be unique per app

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#132]
> 1. operation ids aren’t unique (head & get conflicts and I think there’s just a bug on a post/get for the gen’ed op id)

Originally reported by @sclaussen

**Comment by bajtos** [comment]
The following ids are duplicated:

 - `exists` (`GET /api/mymodels/{id}/exists`, `HEAD /api/mymodels/{id}`)
 - `createChangeStream` (`GET` and `POST` on `/api/mymodels/{id}/createChangeStream`)
