### ISSUE TITLE
Should not include unused definitions

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#133]
> some unused defs - in my case because i haven’t added roles/rolemappings etc (which swagger editor doesn’t like by default)

Originally reported by @sclaussen

**Comment by bajtos** [comment]
I believe this has been already implemented in v2.x, see [loopback-swagger:lib/specgen/type-registry.js](https://github.com/strongloop/loopback-swagger/blob/9ff41f2e1922c02a79dc68381ca528484361eaec/lib/specgen/type-registry.js#L27)

**Comment by bajtos** [comment]
Closing as a duplicate of #143, as the other issue contains all relevant details.
