### ISSUE TITLE
Explorer doesn't generate form data when input arguments maps to `form`

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback-component-explorer#134]
According to [HTTP mapping of input arguments](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-HTTPmappingofinputarguments), the source property could be `form`. After upgrade explorer from 1.8, the explorer doesn't send form data for such endpoints. 

```
Thing.stars = function (star) {
    return Thing.find({ where: { star: star } });
  };

  Thing.remoteMethod(
    'stars',
    {
      accepts    : [
        { arg: 'star', type: 'number', required: true, http: { source: 'form' } }
      ],
      returns    : { arg: 'data', type: 'Thing', root: true }
    }
  );
```
### Reproduce
1. checkout https://github.com/clarkorz/loopback-sandbox/tree/issue/http-source-form
2. `npm install && slc run .`
3. access explorer and find `POST /Things/stars`
4. set arg star to 1 and send request
5. generated curl as follow, no `-d` param

```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://0.0.0.0:3000/api/Things/stars"
```

![screencapture-0-0-0-0-3000-explorer-1446449738833](https://cloud.githubusercontent.com/assets/3261477/10876703/16cbd7e0-817a-11e5-9f20-ed5a02c283c0.png)

**Comment by superkhau** [comment]
Verified. Would you like to submit a PR?

**Comment by dmtux** [comment]
Bug may be closed - fixed by @superkhau https://github.com/strongloop/loopback-swagger/commit/fc15592d6763724e9302b9d7c052b38ddf8b9d78

**Comment by superkhau** [comment]
@dmtux Thanks for confirming. Closing.
