### ISSUE TITLE
Uncaught TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-component-explorer#135]
After updating from 1.x today, I cannot use Explorer because of the following error:

```
Uncaught TypeError: Cannot read property '$ref' of undefinedResolver.resolveTo @ spec-converter.js:537
Resolver.resolveTo @ spec-converter.js:548Resolver.resolve @ spec-converter.js:170
obj.on.response @ resolver.js:529responseInterceptor @ schema-markup.js:399
obj.on.response @ schema-markup.js:403(anonymous function) @ spec-converter.js:70
Request.callback @ index.js:24(anonymous function) @ index.js:24Emitter.emit @ index.js:24xhr.onreadystatechange @ index.js:24
```

I suspect this to be related to the former issue I was having (with the same app):

https://github.com/strongloop/loopback-component-explorer/issues/106

**Comment by fabien** [comment]
It appears this is not the same issue as #106 but hard to debug either way :-(

**Comment by fabien** [comment]
Digging deeper this seems to be related:

https://github.com/swagger-api/swagger-js/issues/85

https://github.com/swagger-api/swagger-ui/issues/1287

In short, attributes of type `array` need to specify the type of its items.

**Comment by fabien** [comment]
It appears to be this TODO: https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/schema-builder.js#L95

**Comment by maxatbrs** [comment]
Hey @fabien I've found that there are a few similar issues regarding this:

https://github.com/swagger-api/swagger-ui/issues/1677

Did you ever get any resolution to this issue and if so what was the solve?

**Comment by superkhau** [comment]
Closing as 1.x is long gone. @fabien Please create a new issue if you still want to take this on.
