### ISSUE TITLE
GeoPoint support is not supported in the explorer

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#136]
@superkhau can you fill in this issue with some details?

**Comment by superkhau** [comment]
Not sure whats going on here. Is this feature request, bug or something that needs triaging?

**Comment by bajtos** [comment]
Starting point: https://github.com/strongloop/loopback-swagger/blob/11bc42930ecccdb667a01122fabec6c7ee37f0ba/lib/specgen/type-registry.js#L7-L14
