### ISSUE TITLE
Create Model from loopback-workspace api /ModelDefinitions - Swagger Object not getting updated

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback-component-explorer#140]
When we create a new model using the loopback-workspace(default :4800/explorer) api POST /ModelDefinitions and calling the loopback-component-explorer to update the newly created models, see below code
```javascript
      var explorer = require('loopback-component-explorer');
      var restApiRoot = app.get('restApiRoot');
      var explorerApp = explorer.routes(app, { basePath: restApiRoot });
      app.use('/explorer', explorerApp);
```

the response for :3000/explorer/swagger.json does not have the newly created models, since the [swaggerObject](https://github.com/strongloop/loopback-component-explorer/blob/master/index.js#L96) in the [index.js](https://github.com/strongloop/loopback-component-explorer/blob/master/index.js) does not getting updated and [returning](https://github.com/strongloop/loopback-component-explorer/blob/master/index.js#L105) updated JSON.

**Comment by 0candy** [comment]
@pktippa  Is this issue waiting on PR#141 to be merged?

**Comment by pktippa** [comment]
@0candy yes, waiting for PR#141 to be merged.

**Comment by 0candy** [comment]
@bajtos  Can you take a look at PR#141? Thanks!

/cc @pktippa

**Comment by bajtos** [comment]
Please use this form when referring to pull requests: #141 or PR #141. That way GitHub automatically creates cross-links.

**Comment by bajtos** [comment]
This issue is a know limitation of the current explorer implementation, I am changing the labels to "enhancement". We need to prioritise this request against other stories in our backlog.

@pktippa perhaps you can take over #141? I am happy to help you along the way of getting it ready to be landed.

**Comment by pktippa** [comment]
@bajtos I am happy to help and collaborate. But I am not sure what I have to do, please clarify and let me know what I have to do next.

**Comment by bajtos** [comment]
@pktippa sorry for the confusion. I thought we were discussing #22. I'll comment on your #141 too.
