### ISSUE TITLE
Model properties with `default: null` break explorer

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-component-explorer#146]
A model with a property containing a `null` default value will produce a Swagger spec that is incompatible with Swagger 2.0, preventing the explorer from loading. The error on the console is:

`Uncaught TypeError: Swagger 2.0 does not support null types ([object Object]).  See https://github.com/swagger-api/swagger-spec/issues/229.`

An example model property is,

```
    "parentNodeId": {
      "default": null
    }
```

The resulting swagger.json looks like this, which is apparently invalid:

```
    "parentNodeId": {
     "default": null,
     "$ref": "#/definitions/ObjectID"
    }
```

Not sure at all what a reasonable solution here is. We're trying to upgrade from `loopback-explorer` but cannot seem to do so without removing our `null` property defaults, which is not an option. Would prefer not to implement a hook to set default values just to make the explorer work.

**Comment by doublemarked** [comment]
FWIW - we've created the following temporary workaround to allow us to move forward despite the problem,

```
  app.get('/explorer/swagger.json', function (req, res, next) {
    var _send = res.send;
    res.send = function (data) {
      if (data && data.definitions) {
        _.forOwn(data.definitions, function (model) {
          _.forOwn(model.properties, function (prop) {
            if (prop.default === null) {
              delete prop.default;
            }
          });
        });
      }
      _send.apply(res, arguments);
    };
    next();
  });
```

**Comment by bajtos** [comment]
Yeah, I have encountered this problem too, it's a bug we should fix. The solution described above, where `default:null` is simply omitted from the swagger output, is a good start :+1:

**Comment by bajtos** [comment]
the catch is how to remove null in nested properties too, for example `default: { enabled: false, port: null }`

**Comment by doublemarked** [comment]
@bajtos Covering that exact case shouldn't be too much trouble, right? Would you be interested in a PR that does post-processing like this inside loopback-boot? 

IMHO this `null` stripping feels like a bandaid. Any thoughts on what the long-term solution is here? On the swagger (OpenAPI) side it seems like they may be moving towards some form of support for null values. May be worth waiting it out?

**Comment by benjaminhon** [comment]
has this been fixed? so null default values are not allowed? I have this problem as well unfortunately

**Comment by yohanesgultom** [comment]
I'm also facing this issue. Could anyone help me suggest how to implement the workaround suggested above (or any better workaround)? I have tried putting the callback in the `server/server.js` but the `_` variable wasn't recognized.

**Comment by yohanesgultom** [comment]
Just a quick update, I just realized that `_` is referring to `lodash` package. So I tried to import it first using `var _ = require('lodash')` in `server/server.js` and the workaround worked as a charm :smile:

**Comment by cstuncsik** [comment]
What if you would remove it recursively?
```
const removeNull = obj => {
  Object.keys(obj).forEach(key => obj[key] === null ? delete obj[key] : removeNull(obj[key]));
  return obj;
};
```

[jsfiddle](https://jsfiddle.net/cstuncsik/uyc0hqj8/)

**Comment by bajtos** [comment]
> Covering that form of nested properties shouldn't be too much trouble, right? Would you be interested in a PR that does post-processing like this inside loopback-explorer?

@doublemarked yes please, a pull request will be very welcome!
