### ISSUE TITLE
Define different views for explorer

### ISSUE THREAD

**Issue by Nautigsam** [strongloop/loopback-component-explorer#149]
Hello, I think that the explorer is useful for not only testing, but also documenting APIs. I would like to expose the explorer to my API's users but I don't want them to see all the routes I use for admin purposes (even if they get 401 code if they try to use it). So it should be possible to define custom options to set different explorer views and mount these views on different routes. Does such options already exist? If not, it could be a cool feature to add.
Just my personal opinion here, but if someone is interested, let's think about it.

**Comment by ananddodia** [comment]
Yes I agree with @Nautigsam 
I have 220+ API's and its difficult to find a particular API. Also it hangs browser when all API's are loaded. Is there a way to set different explorer views based on module and mount these views on different routes?

**Comment by ram33** [comment]
This is really useful feature. If it can't be done, is there a way to generate specs for specific models (subset of swagger.json).

I tried loopback-swagger's generateSwaggerSpec method. I could't find option to filter models.
