### ISSUE TITLE
Support exposing swagger resource listing without ui

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#153]
I should be able to expose the swagger ofr my API without the explorer UI. Some setting like:

```js
"explorer-ui": false
```

Which would default to `true` and when `=== false` the UI would not be mounted as a middleware.

/cc @raymondfeng @bajtos

**Comment by dcversus** [comment]
I think the best way to install loopback-swagger direct and write something like this (is boot script):

```
var generateSwaggerSpec = require('loopback-swagger').generateSwaggerSpec;
module.exports = function(app) {
  var router = app.loopback.Router();
  var swaggerObject = generateSwaggerSpec(app, {});
  router.get('/swagger.json', function(req, res) {
    res.status(200).send(swaggerObject);
  });
  app.use(router);
};
```
I use this way.

**Comment by raymondfeng** [comment]
With https://github.com/strongloop/loopback-component-explorer/issues/154, you can now set `swaggerUI: false` in `server/component-config.json` to disable the UI.
