### ISSUE TITLE
npm run test fails in `overrides swagger-ui files`

### ISSUE THREAD

**Issue by supasate** [strongloop/loopback-component-explorer#161]
`npm run test` fails with the following error.

```1) explorer with custom front-end files overrides swagger-ui files:```
     ```Error: expected '/* custom swagger-ui file */\n' response body, got '// Copyright IBM Corp. 2014. All Rights Reserved.\n// Node module: loopback-component-explorer\n// This file is licensed under the MIT License.\n// License text available at https://opensource.org/licenses/MIT\n\n/* custom swagger-ui file */\n'```

It fails because the content of `dummy-swagger-ui/swagger-ui.js` was prepended with copyright notice.

**Comment by supasate** [comment]
I made a PR #160 to fix this issue.

**Comment by bajtos** [comment]
Fixed by #160.
