### ISSUE TITLE
Export authSchemes and securityDefinitions

### ISSUE THREAD

**Issue by JonnyBGod** [strongloop/loopback-component-explorer#162]
We should be able to export auth specifications with swagger spec.

At least make it easy to hardcode it in options.

**Comment by JonnyBGod** [comment]
It would be perfect if it was possible to easily integrate with loopback-component-oauth2

**Comment by richardpringle** [comment]
@JonnyBGod, should this be in [loopback-swagger/issues](https://github.com/strongloop/loopback-swagger/issues)?

**Comment by gunjpan** [comment]
@JonnyBGod : Could you please post this issue in the correct place as shown above?
Also, a sample/example to understand what you're proposing will definitely help within the description.
Closing this now. Thank you and have a great day!

**Comment by superkhau** [comment]
@JonnyBGod I'm going to help move this issue over to the repo mentioned by @gunjpan and @richardpringle. Please add a better description of your issue there. I'll add a template you can edit there.

**Comment by superkhau** [comment]
This issue was moved to strongloop/loopback-swagger#65
