### ISSUE TITLE
Swagger: skipping unknown type "json".

### ISSUE THREAD

**Issue by windyinwind** [strongloop/loopback-component-explorer#163]
I upgraded loopback-explorer according to README, but when I run `node .`
This message shows up:
`Swagger: skipping unknown type "json" ` 

anyone know what this means? did I do misconfig something?

**Comment by windyinwind** [comment]
sorry, I found what caused this. One dev use 'json' instead of 'object' for param type.

**Comment by loadstarharpal** [comment]
Search for type: "json" in project and replace with type:"Object"
