### ISSUE TITLE
Specifying multiple protocols doesn't work

### ISSUE THREAD

**Issue by sebastianhaas** [strongloop/loopback-component-explorer#165]
Specifying multiple protocols for `loopback-component-explorer` like 

``` javascript
{
  "loopback-component-explorer": {
    "mountPath": "/explorer",
    "host": "localhost:3000",
    "protocol": ["http", "https"]
  }
}
```

results in an invalid `swagger.json`:

``` javascript
...
"host":"localhost:3000",
"basePath":"/api",
"schemes":[["http","https"]]
...
```

I doubt this behaviour is intended because of https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/swagger-spec-generator.js#L130 as well as https://github.com/swagger-api/swagger-ui/issues/1006.

Also see http://swagger.io/specification/, section Schema states that field `schemes` is an array of strings.

I will create a PR to fix it if it is confirmed as a bug.

**Comment by richardpringle** [comment]
That doesn't look right. @sebastianhaas how are you producing the swagger though, I'm not sure that I've seen the component-explorer path produced in a swagger file before...

**Comment by sebastianhaas** [comment]
>  how are you producing the swagger though
I'm not sure if that was your question, but I just navigated to `/explorer/swagger.json`. Given the configuration above, it will result in the invalid output.

**Comment by richardpringle** [comment]
@sebastianhaas, can you for the [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and write the steps to reproduce in the readme?

Thanks in advance.

**Comment by sebastianhaas** [comment]
@richardpringle 
https://github.com/sebastianhaas/loopback-sandbox/tree/issue-165

Hope that works for you!

**Comment by richardpringle** [comment]
@sebastianhaas, there's definitely something wrong here... but I'm not sure that fixing the extra set of brackets addresses much.

What are you doing with the `swagger.json` file? Are you aware of [the API definition generator](https://docs.strongloop.com/display/public/LB/API+definition+generator)?

I'm not sure that the schemes there are entirely relevant to your API in general...

In any case, there should not be an extra set of brackets, so if you want to make the fix, I will try to make sure that the PR gets landed.

**Comment by sebastianhaas** [comment]
I wasn't aware of the API definition generator. However, I don't really see how this matters in regard to the bug I reported. I tried using it, it seems to be broken anyway.

I'm using `swagger.json` to auto-generate an Angular 2 client using `swagger-codegen`.
So yeah. I would prefer if this gets fixed, I mean, why wouldn't it, this is clearly out of specification and you guys are promoting loopback's swagger support quite blatant :)

**Comment by richardpringle** [comment]
I don't believe that "schemes" is doing anything in the context of the explorer. It's not taking into consideration the scheme of the API itself, it's just being set based on the component-explorer configuration.

Even though the swagger.json is "mostly" working for you, that's not the recommended way of grabbing the specification for your API. I think there might be some flaws that you run into if your API gets more complex. 

What was broken with the `export-api-def`?

**Comment by sebastianhaas** [comment]
> I don't believe that "schemes" is doing anything in the context of the explorer. It's not taking into consideration the scheme of the API itself, it's just being set based on the component-explorer configuration.

That might be true, but I wouldn't bet on it. The explorer is using the swagger file itself to determine the endpoints etc., so I suspect the protocol _does_ matter.

Just for the sake of completeness, the actual swagger scheme is built in `loopback-swagger`, with the relevant code for the protocols somewhere here:
https://github.com/strongloop/loopback-swagger/blob/63f734c87704ca9b60e4c9f404b3e733ebe67f5a/lib/specgen/swagger-spec-generator.js#L136

> Even though the swagger.json is "mostly" working for you, that's not the recommended way of grabbing the specification for your API.

What would the recommended way be? `export-api-def` is using https://github.com/strongloop/loopback-api-definition internally, which exports a swagger file, so I really don't see the difference or am I missing something?

**Comment by sebastianhaas** [comment]
@superkhau how can this not be an issue? Afaik there is no way to specify protocols for API definition files, so using loopback:api-def-generator always includes post processing which is needlessly annoying.

Just allow passing options in at https://github.com/strongloop/loopback-api-definition/blob/master/lib/get-api-def.js#L23 so we can at least specify one protocol + host properly.

**Comment by superkhau** [comment]
@sebastianhaas I purposely removed the bug label so someone can take over and confirm the bug and take over where @richardpringle left off as he is not at IBM anymore. "unlabeled" lets us know someone needs to look at this -- when someone decides to take this issue on, you will see the "triage" label applied at that time.

**Comment by sebastianhaas** [comment]
I think this is still an issue that needs to be addressed.

**Comment by sebastianhaas** [comment]
Still open and important.
