### ISSUE TITLE
Explorer doesn't display APIs

### ISSUE THREAD

**Issue by adrielldagasuan** [strongloop/loopback-component-explorer#171]
Explorer says "fetching resource list: http://0.0.0.0:3000/explorer/swagger.json; Please wait.". Checked swagger.json and it's not empty.

<img width="1212" alt="screen shot 2016-07-29 at 9 46 24 pm" src="https://cloud.githubusercontent.com/assets/10193674/17250227/ff008332-55d5-11e6-82e9-fb408db62288.png">

<img width="1216" alt="screen shot 2016-07-29 at 9 47 27 pm" src="https://cloud.githubusercontent.com/assets/10193674/17250261/1ba39204-55d6-11e6-94b3-953ab94bb48a.png">

No customization was done here and files were generated through scaffolding (slc loopback, etc). Anything I could check?

Biboy

**Comment by Yaojian** [comment]
I have the same problem.

**Comment by richardpringle** [comment]
I've seen this before too... it's usually because there is an issue elsewhere within your LoopBack application. Would be great if you guys could fork the [LoopBack sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce your issue in the fork so I can take a look.

**Comment by gunjpan** [comment]
@adrielldagasuan : Does this issue still persist? If yes, could you please provide a repo to reproduce as asked above. Thank you. 
P.S.: I created a new LoopBack app, just now, and it works fine.

**Comment by adrielldagasuan** [comment]
@gunjpan not at the moment. just reinstalled and everything worked. Probably some conflict with some of my ports at that time. thanks! closing this.

**Comment by gunjpan** [comment]
@adrielldagasuan : glad it works, thank you for getting back to me :)

**Comment by codejie** [comment]
I got the same issue...must I re-install everything?

**Comment by imravichaudhary** [comment]
@codejie Copy your swagger.json value to http://editor.swagger.io/#/ and you will be able to check the error within in your swagger file

**Comment by codejie** [comment]
@imravichaudhary thanks for your reply~ I had figured out it, that I set a wrong type of a property in model.json. maybe swagger doesn't support this way, I think.

**Comment by mike-aungsan** [comment]
I have the same issue. Still could not figure it out yet. 
I put a relationships in the model and I realized it does not want I need it and also it break other model creation. 

If I keep it the following line in relationship, it works. But I cannot call locationMapping API.
If I remove it, explorer does not show any API.

location.json:

"relations": {
  "locationName": {
    "type": "embedsMany",
    "model": "locationMapping",
    "property": "ble",
    "options": {
      "forceId": "false",
      "validate": "false",
      "persistent": "true"
    }
  }
}

**Comment by stalinkay** [comment]
The issue can also result from setting `"default"` to `null`.

```
{
  "name": "Exam",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "startDate": {
      "type": "date",
      "required": true,
      "default": null
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
