### ISSUE TITLE
Parameters with x-www-form-urlencoded are not included in the curl commandline and are not sent

### ISSUE THREAD

**Issue by fs523577192** [strongloop/loopback-component-explorer#176]
I have a model called MyInterface.

I am trying to POST "name=Login%20Preparation&url=%2Flogin" with "Parameter content type" "application/x-www-form-urlencode" in http://127.0.0.1:3000/explorer/#!/MyInterface/MyInterface_create.

The curl command line shown is 
`curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" "http://127.0.0.1:3000/api/MyInterfaces"`.

There is no "-d" option in the curl command and I get the response with message "The 'MyInterface' instance is not valid. Details: 'name' can't be blank (value: undefined); 'url' can't be blank (value: undefined).", which I believe is caused by not sending the posted form data.

**Comment by superkhau** [comment]
I'm running into the same issue for API explorer at https://github.com/strongloop/loopback-datasource-juggler/commit/a65504b2aa175e0fc730096975d522e5e06f31a7 for PUT requests using `source: 'form'` for remoting.

**Comment by superkhau** [comment]
Also see comment at https://github.com/strongloop/loopback/issues/2770#issuecomment-250597461

**Comment by bajtos** [comment]
> There is no "-d" option in the curl command and I get the response with message "The 'MyInterface' instance is not valid. Details: 'name' can't be blank (value: undefined); 'url' can't be blank (value: undefined).", which I believe is caused by not sending the posted form data.

This makes perfect sense to me. Because your client send an empty request body, the server rejected the request with a validation error.

The solution is to add (possibly multiple) `-d` options to curl:

```
curl -X POST --header "Content-Type: application/x-www-form-urlencoded" \
  --header "Accept: application/json" \
  -d name=Login%20Preparation -d url=%2Flogin \
  "http://127.0.0.1:3000/api/MyInterfaces"
```

@fs523577192 I may be misunderstanding your bug report. What are you trying to accomplish? What behaviour did you expect from LoopBack?

**Comment by superkhau** [comment]
@bajtos I believe he is talking about the curl line that shows up in API explorer. I ran into the same issue when issueing PUT with form. I expected the curl output from the UI to show -F or -d for JSON, but it simply shows no -d or -F flag and sends no data with the request.

**Comment by bajtos** [comment]
I see. Can we get a sample app reproducing the problem please, so that we stop guessing? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
