### ISSUE TITLE
Migrate to Swagger-UI 3.x

### ISSUE THREAD

**Issue by teaualune** [strongloop/loopback-component-explorer#211]
### Bug or feature request

- [x] Feature request

### Description of feature (or steps to reproduce if bug)

I was originally tracking #124 and found that the latest Swagger UI does the exact thing (`displayOperationId`), so I would ask for project owner if you'd like to migrate Swagger UI to 3.x?

Swagger UI 3.x was almost rewritten (with React.js) and most APIs are incompatible to 2.x, so I'm currently working on the migration but not sure if everyone is satisfy for the new look. Furthermore, I'm not very familiar with the frontend structure of the current Loopback API explorer for now, so there might be some features missed during my migration work.

Here's a brief list about what has been done (or see the actual [codes](https://github.com/teaualune/loopback-component-explorer/tree/feat/swagger-ui-3)):

- [x] update `package.json`, use `swagger-ui-dist` instead of `swagger-ui`
- [x] in `index.js`, change `SWAGGER_UI_ROOT` to `require('swagger-ui-dist').getAbsoluteFSPath()`
- [x] in `index.html`, change importing CSS and JS files
- [x] importing styles from `screen.css` to bring back the old fixed header appearance
- [x] modify `loadSwaggerUI.js` to fit 3.x APIs
- [x] add `displayOperationId: true` to tackle #124

**Comment by drmikecrowe** [comment]
@teaualune Are you still working on this?  I have [this]https://github.com/drmikecrowe/loopback-component-explorer] that I'm working on
