### ISSUE TITLE
Cannot override index.html title using apiInfo

### ISSUE THREAD

**Issue by xnf** [strongloop/loopback-component-explorer#228]
# Description/Steps to reproduce

`uiDirs` configuration allows to specify a custom index.html, but it is an extra effort if I just want to specify the title (in html head and logo). 

Readme refers to `apiInfo` properties, but as far as I can see, [index.html](public/index.html) has hardcoded title. And i did not found any usage of `apiInfo.title` anywhere in the code. Therefore my assumption is - `apiInfo` is not used.

Does it make sense for me to figure out and _improve_ explorer static files or is it something you (contributors/owners) do not want to have?

**Comment by drmikecrowe** [comment]
Just as an FYI, I'm working on a [Swagger-UI v3](https://github.com/drmikecrowe/loopback-component-explorer) port, and that was one of the things [I added](https://github.com/drmikecrowe/loopback-component-explorer/blob/master/public/lib/loadSwaggerUI.js#L33).
