### ISSUE TITLE
example for loopback 4 usage

### ISSUE THREAD

**Issue by DerekTBrown** [strongloop/loopback-component-explorer#229]
Can you add an example for Loopback 4 Usage? It is unclear how this would be used.

**Comment by dhmlau** [comment]
Hi @DerekTBrown , sorry about the late response.  LoopBack 4 is using a different set of dependencies.  All our LoopBack 4 codebase is under `loopback-next` repo.  https://github.com/strongloop/loopback-next. 

For examples and tutorial, please refer to: 
http://loopback.io/doc/en/lb4/Getting-started.html
http://loopback.io/doc/en/lb4/Examples-and-tutorials.html

**Comment by dhmlau** [comment]
@DerekTBrown , I'd like to close this issue as answered.  If you have further questions / comments, please submit under https://github.com/strongloop/loopback-next repo. thanks!
