### ISSUE TITLE
lodash security risk for version 2.7.0

### ISSUE THREAD

**Issue by adrian999999** [strongloop/loopback-component-explorer#241]
# Description/Steps to reproduce
loopback-component-explorer@2.7.0 has a dependency of lodash@@3.10.1 
which has a security risk.

Reference https://nodesecurity.io/advisories/577   

nsp check

# Additional information
Vulnerable    │ <4.17.5  
 Patched       │ >=4.17.5

**Comment by dhmlau** [comment]
@adrian999999 , would you like to submit a PR?

**Comment by bajtos** [comment]
Sorry, the 2.x version is no longer supported, see [here](https://github.com/strongloop/loopback-component-explorer/blob/master/README.md#supported-versions). Please upgrade to a newer version of loopback-component-explorer.
