### ISSUE TITLE
Params not properly added from the UI

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-component-explorer#34]
```js
module.exports = function(Customer) {
  Customer.greet = function(msg, cb) {
    cb(null, 'hello ' + msg); // => prints "hello undefined"
  }

  Customer.remoteMethod('greet', {
    accepts: [{arg: 'msg', type: 'string', http: {source: 'query'}}],
    returns: [{arg: 'greeting', type: 'string'}]
  });
}
```

When using a model like this with a simple remote method, the UI doesn't properly add the `msg` param to the request.

**Comment by bajtos** [comment]
I think this may be already fixed in v2.x, we need to verify.

**Comment by superkhau** [comment]
Performing `curl -XPOST localhot:3000/api/Customers/greet?msg=world`, you get back `hello world`. This is fixed. Closing.
