### ISSUE TITLE
Incorrect model used for "hasMany through" relation methods

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-component-explorer#39]
Consider the example of HasManyThrough relationship described in [docs](http://docs.strongloop.com/display/LB/HasManyThrough+relations):

> The “through” model, Appointment, has two foreign key properties, physicianId and patientId, that reference the primary keys in the declaring model, Physician, and the target model, Patient.

In the explorer UI, the route `POST /patients/{id}/physicians` shows Appointment instead of Physician as the expected request model.

![screen shot 2014-08-13 at 9 54 56](https://cloud.githubusercontent.com/assets/1140553/3902528/2b4a75b6-22bf-11e4-8105-d3a7900a169b.png)

This issue is based on this [StackOverflow question](http://stackoverflow.com/questions/25256741/set-the-custom-properties-in-joining-model-using-loopbacks-hasmanythrough).

**Comment by segnini75** [comment]
Hi, sorry for re open this, but I am actually searching for a solution.
