### ISSUE TITLE
expose validation object to resources/Model 

### ISSUE THREAD

**Issue by Coobaha** [strongloop/loopback-component-explorer#43]
Please check this PR https://github.com/strongloop/loopback-datasource-juggler/pull/259

So we can expose this validation object as json  to explorer as for example (: 
```
   out[name] = {
      id: name,
      properties: properties,
      required: required,
      validations: modelClass.validations || {}
    };
```
and we will get something like this
![image](https://cloud.githubusercontent.com/assets/2446638/4055858/6ffc0508-2daf-11e4-82e4-b66b979cdc8c.png)

but we need to take care about RegExp and other objects transformed to json format.

**Comment by 0candy** [comment]
Would you like to submit a pull request?

**Comment by Coobaha** [comment]
@0candy I will try to do this next weekend

**Comment by Coobaha** [comment]
@0candy this is already implemented with definition schemas :) while bootstraping repo found that examples were not starting, created PR #142

**Comment by 0candy** [comment]
@Coobaha   Thank you for the follow up and thanks for closing the issue.
