### ISSUE TITLE
Config options - disable UI, disable Swagger

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-component-explorer#51]
There should be an easy way how to disable explorer (either UI only or everything) when running in production.

A possible solution: add two new properties to the option object used by middleware factory function.

These two new properties then can be configured either from `server/boot/explorer.js`, or using the upcoming component infrastructure (see https://github.com/strongloop/loopback-example-component/wiki).

**Comment by oakley808** [comment]
+1

**Comment by bajtos** [comment]
@ricardohbin @oakley808 Can you contribute this feature yourself?

**Comment by bajtos** [comment]
On the second thought, I don't think it makes sense to disable the UI while keeping the Swagger metadata available. With metadata available, one can run an own copy of the Swagger UI (e.g. via  http://petstore.swagger.io/) and configure it with the Swagger metadata provided by the LoopBack server. 

See also https://github.com/strongloop/loopback/issues/1134, it points out a similar problem.

Here is the solution I would like to see implemented instead: extend loopback-boot's support for `component-config.json` (see https://github.com/strongloop/loopback-boot/pull/86) to allow developers to enable/disable components on per-environment basis.

At the moment, explorer can be configured as follows:

```js
// server/component-config.json
{
  "loopback-explorer": {
    // config
  }
}
```

We need to extend loopback-boot so that a component like loopback-explorer can be disabled in production via the following JSON file:

```js
// server/component-config.production.json
{
  "loopback-explorer": null
}
```

@raymondfeng Thoughts? This is similar to (but not the same as) the way how middleware can be disabled on per-environment basis via `server/middleware.production.json`. I am also aware that this feature is useful for 2.x only, as https://github.com/strongloop/loopback-boot/issues/93 will obsolete it.

/cc @PradnyaBaviskar

**Comment by raymondfeng** [comment]
@bajtos With your proposal, do we need to change the loopback-explorer code to accept the config object and decide if itself should be disabled?

**Comment by bajtos** [comment]
No, loopback-explorer does not need to be changed, this feature will be handled by loopback-boot. That's why I am proposing `loopback-explorer: null` as opposed to `loopback-explorer: { enabled: false }`.

**Comment by raymondfeng** [comment]
OK, so if `loopback-explorer: null` or `loopback-explorer: false` is configured, `loopback-boot` doesn't even bother to load the `loopback-explorer` component, right? If so, I'm +1.

BTW, we should consider to use this convention to `remove/disable` properties inherited from base models.

**Comment by bajtos** [comment]
> OK, so if `loopback-explorer: null` or `loopback-explorer: false` is configured, loopback-boot doesn't even bother to load the loopback-explorer component, right? If so, I'm +1.

Yes, that's the plan

> BTW, we should consider to use this convention to remove/disable properties inherited from base models.

I am fine with that, thought it's completely out of scope of this issue.

**Comment by ricardohbin** [comment]
surely @bajtos, I can give a look at this ;)

**Comment by bajtos** [comment]
The loopback-boot change has been landed via https://github.com/strongloop/loopback-boot/pull/103, let me know if it works for you.

**Comment by voitau** [comment]
Tried to use as suggested in documentation:
```
{
  "loopback-component-explorer": false
}
```
Works if no overrides. If original ```component-config.json``` has any configuration options defined, then override with ```false`` fails and the app exits. Does anyone else experience the same issue?

**Comment by bajtos** [comment]
> @voitau Works if no overrides. If original component-config.json has any configuration options defined, then override with false fails and the app exits. Does anyone else experience the same issue?

This is off-topic for this GH issue. Please open a new issue for the problem and provide steps for reproducing the issue on our machines, see [wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by alFReD-NSH** [comment]
This is still an issue because setting `loopback-explorer: null` or `loopback-explorer: false` in component-config.production.json doesn't override `loopback-explorer: { ... }`.

Here's a test for loopback-boot to replicate the issue:

diff --git a/test/executor.test.js b/test/executor.test.js
index 52564af..a6f716b 100644
--- a/test/executor.test.js
+++ b/test/executor.test.js
@@ -756,6 +756,24 @@ describe('executor', function() {
       appdir.resolve('components/test-component/index.js'));
   });
 
+  it('disable component if overrided by production configuration', function() {
+    appdir.writeConfigFileSync('component-config.json', {
+      './components/test-component': {}
+    });
+    appdir.writeConfigFileSync('component-config.production.json', {
+      './components/test-component': null
+    });
+
+    appdir.writeFileSync('components/test-component/index.js',
+      'module.exports = ' +
+      'function(app, options) { app.componentOptions = options; }');
+
+    boot(app, { appRootDir: appdir.PATH, env: 'production' });
+
+    expect(Object.keys(require.cache)).to.not.include(
+      appdir.resolve('components/test-component/index.js'));
+  });
+
   it('configures middleware (that requires `this`)', function(done) {
     var passportPath = require.resolve('./fixtures/passport');

**Comment by bajtos** [comment]
> @alFReD-NSH This is still an issue because setting loopback-explorer: null or loopback-explorer: false in component-config.production.json doesn't override loopback-explorer: { ... }.

Could you please open an issue in loopback-boot? Submitting a patch fixing the issue would be even better :)

**Comment by alFReD-NSH** [comment]
There's already in an issue opened there: strongloop/loopback-boot#146

I'll be submitting a pr soon.
