### ISSUE TITLE
Add option to support authorization header instead of query params for access tokens

### ISSUE THREAD

**Issue by simonguest** [strongloop/loopback-component-explorer#97]
Currently, access tokens (set in the top right of the explorer) are passed as query parameters (e.g. /api/test?access_token=1234).

Many exposed APIs, especially those using OAuth, should pass this token as an authorization header (e.g. token would be set in UI as normal, but would be passed as OAuth or Bearer authorization header).

It would be great to have an option in explorer to support this.

**Comment by tallboy** [comment]
+1 from me.  I'm proxy-ing some API requests to another api that wants an Authorization header using an OAuth2 header.  It's rendered the Loopback Explorer pretty much useless to me and I'm forced to use Paw to test APIs.  Is there a Loopback feature that lets someone expose headers to send with requests i.e. set / add `req.headers` to requests coming from the loopback-explorer?

**Comment by STRML** [comment]
I agree that this should be an option; until then, you can add it yourself:

Initialize loopback-explorer with the option:

```javascript
require('loopback-explorer')(app, {uiDirs: ['./swagger']});
```

Then create a folder `./swagger` and add a new `index.html`. Then you can add any scripts you like to the init. Swagger runs [Shred](https://github.com/pandastrike/shred) for AJAX, I'm sure there's some sort of preauth hook you could use. Have it check `window.authorizations`.

**Comment by tallboy** [comment]
Sweet... Thanks @STRML! I'll play around with it and let you know how it goes.

**Comment by 0candy** [comment]
Would you like to submit a pull request?
